config/routes.rb
Rails.application.routes.draw do
  get "users/index"
  get "users/new"
  get "users/create"
  get "users/edit"
  get "users/update"
  get "users/destroy"

  # Rota para buscar funcionários por setor
  get "/sectors/:sector_id/employees", to: "sectors#employees"


  authenticated :user do
    root "visits#index", as: :authenticated_root
  end

  devise_scope :user do
    root to: "devise/sessions#new" # Página de login como root padrão
  end

  # Página de busca de visitantes
  get "/visitors/search", to: "visitors#search"

  # Permite a confirmação de visitas apenas por funcionários (Patch)
  resources :visits do
    member do
      patch :confirm
    end
  end

  devise_for :users

  resources :visits
  resources :visitors do
    member do
      patch :deactivate
      patch :activate
    end
  end

  resources :employees do
    member do
      patch :deactivate
      patch :activate
      get :reactivate
    end
  end

  resources :sectors do
    member do
      patch :deactivate
      patch :activate
    end
  end

  resources :units do
    member do
      get :sectors
      patch :deactivate
      patch :activate
    end
  end

  resources :users, except: :show  # CRUD de usuários para admin

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <div class="sidebar-header">
    <h3>VisitControl</h3>
  </div>

  <ul class="nav flex-column">

    <% if user_signed_in? %>
      <% if current_user.admin? %>
        <li class="nav-item">
          <%= link_to users_path, class: "nav-link" do %>
            <i class="fas fa-user-cog"></i> Usuários
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to employees_path, class: "nav-link" do %>
            <i class="fas fa-users"></i> Funcionários
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to units_path, class: "nav-link" do %>
            <i class="fas fa-building"></i> Unidades
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to sectors_path, class: "nav-link" do %>
            <i class="fas fa-sitemap"></i> Setores
          <% end %>
        </li>
      <% end %>

      <% if current_user.attendant? || current_user.employee? %>
        <li class="nav-item">
          <%= link_to visits_path, class: "nav-link" do %>
            <i class="fas fa-calendar-check"></i> Visitas
          <% end %>
        </li>
        <% if current_user.attendant? %>
          <li class="nav-item">
            <%= link_to visitors_path, class: "nav-link" do %>
              <i class="fas fa-id-badge"></i> Visitantes
            <% end %>
          </li>
        <% end %>
      <% end %>

      <li class="nav-item user-info">
        <span><i class="fas fa-user"></i> Olá, <%= current_user.email.split('@').first %></span>
      </li>

      <li class="nav-item">
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger w-100" %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "btn btn-primary w-100" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sistema Visitas" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'visits_form.js', crossorigin: 'anonymous' %>
    <%= javascript_include_tag 'sectors_filter.js', crossorigin: 'anonymous' %>

    <%= javascript_importmap_tags %>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">

    <!-- Select2 -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  </head>

  <body>
    
    <div class="dashboard">
      <!-- Barra lateral -->
      <%= render "layouts/sidebar" %>

      <!-- Conteúdo da página -->
      <div class="body-container">
        <%= yield %>
      </div>
    </div>


    <!-- Bootstrap script -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
  </body>
</html>